### ISSUE TITLE
bk-ci踩坑记

### ISSUE THREAD

**Issue by zanyzhao** [Tencent/bk-ci#1132]
## 部署
- [x] 部署脚本及template中出现大量bkee字眼，应全部去掉 
- [x] gateway模块部分lua配置没有被render导致consul调用失败 @freyzheng 
- [x] 安装命令中关于gateway部署的部分未更新`gateway/core` @freyzheng 
- [x] 统一安装目录到`bkce/ci`下，目前有些地方叫`bkci`，有些叫`ci`
- [x] log模块配置连接ES有问题
```yaml
elasticsearch:
  ip: 127.0.0.1
  port: 9200
  cluster: __CLUSTER_NAME__
  name: __CLUSTER_NAME__
```
### BUG
- [x] 新建项目不符合条件时提示信息不对 
![image](https://user-images.githubusercontent.com/1629409/79589278-bf274f00-8107-11ea-8ea2-e438058a28ac.png)
- [x] 本地部署多套bk-ci时，默认项目会互相串 @lockiechen 

### 体验
- [x] 居中
![image](https://user-images.githubusercontent.com/1629409/79595146-eafb0280-8110-11ea-9b5e-c7177dcbac8b.png)
