### ISSUE TITLE
有关docker 版bk-ci 无法读取构建日志

### ISSUE THREAD

**Issue by ypsliu** [Tencent/bk-ci#183]
访问log 微服务报错 无法找到日志

**Comment by parkerzhu** [comment]
遇到同样的问题

**Comment by gaoyining** [comment]
etc 下的 application-assembly.yml
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  cluster: bkee-es

加入  cluster: bkee-es

**Comment by irwinsun** [comment]
各位，请问有没有日志堆栈

**Comment by zanyzhao** [comment]
@gaoyining 亲测还要加上这个：
```yml
elasticsearch:
  ip: 127.0.0.1
  port: 9200
  cluster: __CLUSTER_NAME__
  name: __CLUSTER_NAME__
```
可以关注下 #1132
