### ISSUE TITLE
feat: 配置文件中的密钥迁移

### ISSUE THREAD

**Issue by irwinsun** [Tencent/bk-ci#5050]
示例（不止一处）：
[application-store.yml](https://github.com/Tencent/bk-ci/blob/master/support-files/templates/%23etc%23ci%23application-store.yml)
下有类似
```yaml
aes:
  # 部署前修改好，后续升级如果再修改，会导致历史数据读取不了，所以如果修改需要先解密重新入库
  aesKey: "J%k^yO{?vt}3tXpG"
  aesMock: "******"

```
默认配置，因早期设置的是一个随机生成的， 配置没有修改, 现在需要开发出迁移转换OP接口，供现有用户部署后进行调用，
传入新钥和旧钥，对现有数据进行重新加密。

同时修改配置用占位符号替换
```yaml
aes:
  # 部署前修改好，后续升级如果再修改，会导致历史数据读取不了，所以如果修改需要先解密重新入库
  aesKey:  "__BK_CI_STORE_AES_KEY__"
  aesMock: "******"

```
