### ISSUE TITLE
feat: 矩阵策略fromJson解析优化

### ISSUE THREAD

**Issue by royalhuang** [Tencent/bk-ci#6099]
支持如下写法：

```
matrix:

  app: ${{ fromJSON(variables.APP_LIST) }}

matrix:

  app: ${{ fromJSON(variables.APP_LIST) }}

  include: ${{ fromJSON(variables.a) }}

  exclude: ${{ fromJSON(variables.a) }}
```
