### ISSUE TITLE
【stream】手动触发时，支持修改入参值

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#6997]
**What would you like to be added**:
触发器 on 下，新增触发方式manual
```
on:
  manual: enabled  # 是否允许手动触发，缺省时默认为 enabled，可选值： enabled / disabled
  openapi: enabled # 是否允许openapi触发，缺省时默认为 enabled，可选值： enabled / disabled

variables:
  a: 123
  my_val_1:
    value: 1,2,3                    # 默认值，需要在 values 中
    readonly: true
    allow-modify-at-startup: true   # 手动触发/openapi触发时生效，可选值：true / false，默认为 false，当 false 时
    props:
      label: 我是预定义下拉可选值的字段 # [可选]
      type: selector
      options:
        - id: 1
          label: 正式环境
          description: 说明什么情况下发正式
      multiple: true                  # [可选] 是否允许多选，缺省时为 false（type=selector时生效）
      description: 这是个允许多选的下拉选择字段
  my_val_2:
    value: my_const_value
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      label: 我是通过url获取下拉可选值的字段
      type: selector      
      datasource:
        url: ""                      # [可选]获取下拉列表中可选值的接口，需要接入蓝鲸网关
        data-path: ""                # [可选]选项列表数据所在的、API返回体json中的路径，没有此字段则默认为data， 示例：data.detail.list。配合url使用
        param-id: ""                 # [可选]url返回规范中，用于下拉列表选项id的字段名，配合url使用
        param-name: ""               # [可选]url返回规范中，用于下拉列表选项label的字段名，配合url使用
        has-add-item: true           # [可选]是否有新增按钮
        item-text: ""                # [可选]新增按钮文字描述
        item-target-url: ""          # [可选]点击新增按钮的跳转地址
      multiple: true                 # [可选]是否允许多选，缺省时为 false（type=selector时生效）
      description: 这是个允许多选的下拉选择字段
  my_val_3:
    value: true
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      label: 我是 BOOL 字段
      type: boolean
  my_val_4:
    value: 1,2
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      label: 我是 checkbox 字段
      type: checkbox
      options:
        - id: 1
          label: 正式环境
          description: 说明什么情况下发正式
  my_val_5:
    value: 这是个tips,说明下怎么使用
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      type: tips
```
- on 关键字支持 manual/openapi 属性
- variables 下的字段支持设置是否允许启动时修改：allow-modify-at-startup
  - readonly 为 true 时，在流水线执行过程中不能动态变更变量值，和 allow-modify-at-startup 不冲突
- 当允许启动时修改时，支持定义手动触发时如何展示，一期支持如下类型
    - vuex-input
    - vuex-textarea
    - selector：支持配置是否允许多选
    - checkbox
    - boolean
    - company-staff-input
    - tips
-  每个入参支持设置是否必填、默认为非必填：required
- 当多选时，多个选中的值以逗号分隔
- 支持禁用手动触发
```
on:
  manual: disabled
```
禁用后，不能手动触发（以选择的分支上的配置为准）
- 为了兼容历史数据，不配置manual 以及不配置on 时，默认行为同如下配置一致：
```
on:
  manual: enabled
```
- 手动触发时，页面UI示例：
    - 选择分支后，拉取对应分支上的手动触发参数设置，渲染
    - 参数未渲染结束前，不能提交
    - 如果参数很多，有滚动条，提交/取消按钮浮动在当前屏底部
<img width="717" alt="企业微信截图_2f72221e-5541-4d09-9464-505bf82afe3f" src="https://user-images.githubusercontent.com/54432927/173558206-2b78b049-d24f-4e6c-b06b-412f860a068c.png">

**注意**
- 目前的版本对应的 openapi 不做任何变更，沿用旧逻辑
- 目前的版本的页面触发功能暂时隐藏，新加 run/执行 入口实现此需求

**Why is this needed**:
