### ISSUE TITLE
job 下通过env关键字修改 PATH 配置时，agent无法启动问题优化

### ISSUE THREAD

**Issue by fayewong-v5** [Tencent/bk-ci#7734]
**What would you like to be added**:
当在 job 下通过 env 关键字修改 PATH 时，构建机无法正常启动：
```
jobs:
  linux:
    name: linux
    env:
      PATH: /xxx:$PATH
```
希望支持如上用法，允许通过 env 关键字修改 PATH

**Why is this needed**:
1、用户在 env 下的设置，不应该影响蓝盾 agent 的运行
2、支持用户修改当前 job 的PATH
